apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi # should be same as volume we created
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: # provide volumeid of the volume created in aws
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: topology.kubernetes.io/zone
  #             operator: In
  #             values:
  #               - us-east-1d
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  5Gi # should to equal to less than PV storage but we cannot request not more than that
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
  labels:
    purpose: ebs-static
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v hostpath:containerpath
    - name: ebs-static-pv
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-static-pv
    persistentVolumeClaim:
      claimName: ebs-static-claim
---
apiVersion: v1
kind: Service 
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static
  ports:
  - name: nginx-svc-port
    protocol: tcp
    port: 80 # this is service port
    targetport: 80 # this is container port.
    nodePort: 30007