apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "expense-ebs" 
 # volumeName: ebs-dynamic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  3Gi # should to equal to less than PV storage but we cannot request not more than that
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic
  labels:
    purpose: ebs-dynamic
spec:
  #nodeSelector:
   # topology.kubernetes.io/zone: us-east-1d
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v hostpath:containerpath
    - name: ebs-dynamic
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-dynamic
    persistentVolumeClaim:
      claimName: ebs-dynamic
---
apiVersion: v1
kind: Service 
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic
  ports:
  - name: nginx-svc-port
    protocol: tcp
    port: 80 # this is service port
    targetport: 80 # this is container port.
    