apiVersion: v1
kind: Service # this creates ClusterIP service
metadata:
  name: nginx
spec:
  selector:
    project: expense
    component: backend
    environment: dev
  ports:
  - name: nginx-svc-port
    protocol: tcp
    port: 80 # this is service port
    targetport: 80 # this is container port. we can also give name and provide value in pod definition


