apiVersion: v1
kind: Deployment
metadata:
  name: nginx
  labels: # these are replicaset labels
    app: nginx
    tier: frontend
spec:
  replicas: 3 # we can give how many replicas we need 
  selector: # these are used to select the pod to create replicas
    matchLabels:
      app: nginx
      tier: frontend
  template: # this is pod definition
    metadata:
      labels:
        app: nginx
        tier: frontend         
    spec:
      containers:
        name: nginx
        image: nginx

---
apiVersion: v1
kind: Service # this creates ClusterIP service
metadata:
  name: nginx
spec:
  selector:
   app: nginx
   tier: frontend
  ports:
  - name: nginx-svc-port
    protocol: tcp
    port: 80 # this is service port
    targetport: 80 # this is container port. we can also give name and provide value in pod definition
